# Generated by Django 3.1 on 2020-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scription',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
