# Generated by Django 3.1 on 2020-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_scription'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], default='full-time', max_length=20),
        ),
    ]
